version: '3'
services:
  app_node_one:
    build: .
    command: ['./.wait-for-it.sh', '--host=mysqldb', '--port=$MYSQL_PORT', '--', 'nodemon']
    volumes:
      - '/usr/src/app/node_modules'
      - './:/usr/src/app'
    env_file: .env
    links:
      - mysqldb

  mysqldb:
    image: mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    container_name: ${MYSQL_HOST}
    logging:
      driver: 'none'
